# KMEANS E DBSCAN

In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [85]:
X_random, y_random = datasets.make_moons(n_samples = 1500, noise = 0.75)

In [86]:
import plotly.express as px
grafico = px.scatter(x= X_random[:, 0], y = X_random[:, 1])
grafico.show()

In [90]:
from sklearn.cluster import KMeans
treino = KMeans(n_clusters= 3)
centers = treino.fit_predict(X_random)

In [91]:
centers

array([2, 0, 1, ..., 2, 2, 1])

In [92]:
grafico = px.scatter(x = X_random[:, 0], y = X_random[:, 1], color=centers)
grafico.show() # algoritmo eh compativel para o conjunto de dados com ruido

In [93]:
np.unique(centers, return_counts=True)

(array([0, 1, 2]), array([416, 513, 571], dtype=int64))

# DBSCAN

In [94]:
X_random, y_random = datasets.make_moons(n_samples = 1500, noise = 0)

In [95]:
from sklearn.cluster import DBSCAN

In [96]:
train = DBSCAN(eps = 0.5, min_samples= 5)
rotulos = train.fit_predict(X_random)

In [97]:
rotulos

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [98]:
np.unique(rotulos, return_counts=True) # otimo

(array([0, 1], dtype=int64), array([750, 750], dtype=int64))

In [99]:
grafico = px.scatter(x = X_random[:, 0], y = X_random[:, 1], color = rotulos)
grafico.show() # o algoritmo nao eh compativel quando os dados possuem ruido.

# Agglomerative clustering HIERARCHE CLUSTERING

In [100]:
from sklearn.cluster import AgglomerativeClustering
X_random, y_random = datasets.make_moons(n_samples = 1500, noise = 0.75)

In [101]:
treino = AgglomerativeClustering(n_clusters = 2, affinity = 'euclidean', linkage='ward')
rotulos = treino.fit_predict(X_random)

In [102]:
rotulos

array([1, 1, 0, ..., 0, 1, 1], dtype=int64)

In [103]:
np.unique(rotulos, return_counts=True)

(array([0, 1], dtype=int64), array([802, 698], dtype=int64))

In [104]:
graf = px.scatter(x = X_random[:, 0], y = X_random[:, 1], color = rotulos)
graf.show() # MELHOR QUANDO OS DADOS POSSUEM RUIDO